'use strict';

module.exports = {
  TOTAL_INVENTORY: 'TOTAL_INVENTORY',
  DISTRIBUTOR_LIST: 'DISTRIBUTOR_LIST',
  BALANCE_CHANGE: 'BALANCE_CHANGE',
  RETIRED_TX: 'RETIRED_TX',
  VAULT: 'VAULT',
  ASSET_TYPE: 'ASSET_TYPE',

  // USERS
  SAFE_GOLD_USER: 'SAFE_GOLD_USER',
  BUY_GOLD: 'BUY_GOLD',
  SELL_GOLD: 'SELL_GOLD',
  REDEEM_GOLD: 'REDEEM_GOLD',
  GIFT_GOLD: 'GIFT_GOLD',
  GOLD_TX: 'GOLD_TX',

  // VAULT
  ADD_GOLD_PROPOSAL: 'ADD_GOLD_PROPOSAL',
  REMOVE_GOLD_PROPOSAL: 'REMOVE_GOLD_PROPOSAL',
  SAFE_GOLD_BALANCE: 'SAFE_GOLD_BALANCE',
  TEMP_STORAGE: 'TEMP_STORAGE'
};
